version: '2'

services:

  nginx:
    extends:
      file: docker-compose.base.yaml
      service: nginx
    environment:
      VIRTUAL_HOST: ${APPLICATION_DOMAIN}
      LETSENCRYPT_HOST: ${APPLICATION_DOMAIN}
      LETSENCRYPT_EMAIL: ${APPLICATION_CERT_EMAIL}

  php:
    extends:
      file: docker-compose.base.yaml
      service: php
    environment:
      APPLICATION_BASE_URL: ${APPLICATION_BASE_URL}
      SMTP_MAILHUB: ${SMTP_MAILHUB}
      SMTP_REWRITE_DOMAIN: ${SMTP_REWRITE_DOMAIN}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_USE_TLS: "YES"
      SMTP_AUTH_METHOD: LOGIN
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

  mysql:
    extends:
      file: docker-compose.base.yaml
      service: mysql

  proxy:
    image: jwilder/nginx-proxy
    container_name: mood_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./var/nginx/certs:/etc/nginx/certs
      - ./var/nginx/vhost.d:/etc/nginx/vhost.d
      - ./var/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: mood_letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
