CREATE SCHEMA IF NOT EXISTS `mood`;

USE `mood`;

CREATE TABLE IF NOT EXISTS `task` (
  `id` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
